micronaut:
  application:
    name: cowinAlert
  router:
    static-resources:
      default:
        enabled: true
        mapping: "/public/**"
        paths: "classpath:public"
jpa:
  default:
    packages-to-scan:
        - 'com.softclinic.cowin'
    properties:
      hibernate:
        hbm2ddl:
          auto: create-drop
        show_sql: true

datasources:
  default:
    url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE;DATABASE_TO_UPPER=false;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2

